import { ROLES } from "./roles.js";

export const PERMISSIONS = {
  MANAGE_USERS: "MANAGE_USERS",

  VIEW_ALL_CHATS: "VIEW_ALL_CHATS",

  VIEW_DEPARTMENT_CHATS:
    "VIEW_DEPARTMENT_CHATS",

  MANAGE_LEADS: "MANAGE_LEADS",

  ASSIGN_LEADS: "ASSIGN_LEADS",

  VIEW_ANALYTICS: "VIEW_ANALYTICS",

  TRAIN_AI: "TRAIN_AI",

  USE_CHATBOT: "USE_CHATBOT",
};