import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  ADMIN: Object.values(PERMISSIONS),

  CEO: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.CONTACT_VIEW,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
  ],

  CTO: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USER_VIEW,
  ],

  CFO: [
    PERMISSIONS.DASHBOARD_VIEW,
  ],

  sales_manager: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,

    PERMISSIONS.CONTACT_VIEW,
    PERMISSIONS.CONTACT_CREATE,
    PERMISSIONS.CONTACT_UPDATE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
  ],

  sales_executive: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,

    PERMISSIONS.CONTACT_VIEW,
    PERMISSIONS.CONTACT_CREATE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
  ],

  customer_support: [
    PERMISSIONS.CONTACT_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.WHATSAPP_VIEW,
    PERMISSIONS.WHATSAPP_SEND,
  ],

  USER: [],
};